/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MenuPrincipalController;

/**
 *
 * @author marcu
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private final MenuPrincipalController controller;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        this.controller = new MenuPrincipalController(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemAcdastroAluno = new javax.swing.JMenuItem();
        jMenuOperações = new javax.swing.JMenu();
        jMenuItemLista = new javax.swing.JMenuItem();
        jRadioButtonMenuItemBusca = new javax.swing.JRadioButtonMenuItem();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/capa-blog-diferenciar-escola-min-1024x683.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 659, 374));

        jMenuCadastro.setText("Cadastro");

        jMenuItemAcdastroAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Icons/cliente-icon.png"))); // NOI18N
        jMenuItemAcdastroAluno.setText("Aluno");
        jMenuItemAcdastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcdastroAlunoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemAcdastroAluno);

        jMenuBar1.add(jMenuCadastro);

        jMenuOperações.setText("Operações");

        jMenuItemLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Icons/relatorioTrabalho-icon.png"))); // NOI18N
        jMenuItemLista.setText("Lista");
        jMenuItemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaActionPerformed(evt);
            }
        });
        jMenuOperações.add(jMenuItemLista);

        jRadioButtonMenuItemBusca.setSelected(true);
        jRadioButtonMenuItemBusca.setText("Busca");
        jRadioButtonMenuItemBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/Icons/agenda-icon.png"))); // NOI18N
        jRadioButtonMenuItemBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemBuscaActionPerformed(evt);
            }
        });
        jMenuOperações.add(jRadioButtonMenuItemBusca);

        jMenuBar1.add(jMenuOperações);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaActionPerformed
this.controller.navegarParaLista();
    }//GEN-LAST:event_jMenuItemListaActionPerformed

    private void jMenuItemAcdastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcdastroAlunoActionPerformed
this.controller.navegarParaCadastroAluno();
    }//GEN-LAST:event_jMenuItemAcdastroAlunoActionPerformed

    private void jRadioButtonMenuItemBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemBuscaActionPerformed
this.controller.navegarParaBusca();        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItemBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAcdastroAluno;
    private javax.swing.JMenuItem jMenuItemLista;
    private javax.swing.JMenu jMenuOperações;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemBusca;
    // End of variables declaration//GEN-END:variables
}
